version: '3.9'

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: ./src
    ports:
      - "8000:8000"
    volumes:
      - './src:/app/src'
      - './db.sqlite3:/app/src/db.sqlite3'
    command: ["python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]

  celery:
    restart: always
    build:
      context: ./src
    volumes:
      - './src:/app/src'
      - './cats:/cats'
    command: celery --workdir=./src -A webapp worker -l INFO

  flower:
    restart: always
    build:
      context: ./src
    volumes:
      - './src:/app/src'
      - './cats:/cats'
    command: celery --workdir=./src -A webapp flower
    ports:
      - "5555:5555"

  beats:
    build:
      context: ./src
    volumes:
      - './src:/app/src'
      - './cats:/cats'
      - './db.sqlite3:/app/src/db.sqlite3'

    command: celery --workdir=./src -A webapp beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler


